### ISSUE TITLE
ambiguous redirect problem

### ISSUE THREAD

**Issue by ylaaross** [ylaaross/minishellUP#1]
i don't know all the cases of ambiguous redirection in shell ,i want to creat my own shell project so it would be a pleasure if someone helps

**Comment by abdelkarimhajji** [comment]
i know some cases for example if there is a empty variable like for example you declare a var like that export x="" and you want to do redirection to it will display an error message of ambiguous there is another case when for example you declare a var like this export x="ss sss" with a space between words it will declare the same issue i hope you did understand well.
